AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MySecurityGroup:
    Type: String
    Description: Enter the security group
  SecurityGroupPort:
    Type: Number
    Description: Provide the port number to be associated with your security group
    MinValue: 22
    MaxValue: 65535
    ConstraintDescription: The port number must be between 1150 and 65535

  InstanceType:
    Type: String
    Description: Enter the instance type you would like to use
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
      - t2.nano
    ConstraintDescription: Must be a valid EC2 instance

  ImageID:
    Type: String
    Default: ami-

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Enter in the key pair to authenticate to your instance
    ConstraintDescription: Must be a valid keypair

  SecurityGroupIngressCIDR:
    Type: String
    Description: The IP address range that can have access to the EC2 instance
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP address

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName

  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Create a security group and allow specific ports
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
          IpProtocol: tcp
